name: web
namespace: vc-geni
replicas: 1
enabled: true
image: 442426895473.dkr.ecr.us-east-1.amazonaws.com/ust-vc/web:3fc520-2025-03-27
port: 80
targetport: 80
protocol: TCP
type: LoadBalancer
env:
  - envname: NODE_ENV
    envvalue: "edge"
volumeMounts:
- name: web-secret
  mountPath: /usr/src/app/src/config/profiles/
  readOnly: false
volumes:
- name: web-secret
  secret:
    secretName: web-secret
pvc:
  enabled: false

 
