# values.yaml
replicaCount: 1

image:
  repository: 442426895473.dkr.ecr.us-east-1.amazonaws.com/sftp-vc
  tag: pim-fe-env
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080


env:
  CUSTOMER: "democa"
  CUSTOMER_NAME: "UST"
  VERSION: "V 3.1.1"
  DOMAIN: ".fc-ust.com"
  OAUTH_URL: "https://democa-api.fc-ust.com/oauth/token"
  OAUTH_TOKEN: "Basic dXN0and0Y2xpZW50aWQ6dXN0UmQ5M0NmNFdfRm13WiY="

resources: {}
