apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiggy
  namespace: swiggy
spec:
  ingressClassName: dagility-nginx-ingress   # Replace with your actual ingress class, e.g., 'nginx' or 'dagility-nginx-ingress'
  tls:
  - hosts:
    - swiggyclone.test.ustpace.com  # Use the correct domain
    secretName: tls-rancher  # The secret that Rancher uses to manage the wildcard cert
  rules:
  - host: swiggyclone.test.ustpace.com  # The same domain as in the tls section
    http:
      paths:
      - backend:
          service:
            name: swiggy-service
            port:
              number: 3000
        path: /
        pathType: Prefix
