{{- if .Values.pvc}}
{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "1Gi" }}
  storageClassName: {{ .Values.pvc.storageClass | default "local-path" }}
{{- end }}
{{- end }}

---
