repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: prometheus
  chart: prometheus-community/prometheus
  namespace: prometheus
  values:
  - ../helmvalues/prometheus.yaml
  version: 27.5.0
