# Default values for pim-fe application
replicaCount: 1

image:
  repository: 860602188711.dkr.ecr.us-east-1.amazonaws.com/pim-fe
  tag: 28
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

imagePullSecrets:
  - name: my-ecr-secret
imagePullSecretEncoded: |
  ewoJImF1dGhzIjogewoJCSI4NjA2MDIxODg3MTEuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdz
  LmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsTldFNVhaREZz
  TkU1VWJHcFNibFpxVVRCV2VWVlhaSGRVUmxKelRraGtUVk15Vm5aVVIxRTBWVEpPTWxsWWFFSlVS
  MXBXV2tkMGJWSjZiRVZNTVdjeFZqTlNNazB4YkVKUmF6bElVbXhaZVZaWFpHNU9NbEpwWlVSR00y
  TXhUVFZqTTJSWVV6RkdWMk13VFhabFIwVXlWREpXZGxaWWFHbFZWVVpzWkRCR1lWTlZNSGxPV0Zv
  MlRrVXdNMHd6VVRKVFIzQllXbFpTVTJONlFrbFZNazF5VDBab1ZtUlhUWGxaTWswMVlWYzFjR05J
  V2pKTlZFNTFUMVpzVGxWSFdYZFZNa3BKVFZkd1EyTXpUalZsUkZwYVUwVndObFZYVGxGaVUzUklV
  bTFzY0ZsVVNrZFVNR1J3Wkd4YVNXRXpjSEprYkU0MlpVVm9kMUZ0Y0c1amJtaHBVa2hzU1dScWFH
  RlhXRnBFVW10d05GRnFSbFZMTTFJMVVqTm9OVTFyZUZSV2FscDRWRmhTV21KWFRrbGlhMHB6WTBW
  Uk5VNUlXazFUVmtwVlRETldjRmw2VVRSWGEwWTBTekJXU1ZGVlZuUlNXRWswVVRGU1IwNHdVa3hQ
  Vm1oSFRXeHJjbVZVV2s1UFIyaDJWbXQwUWxwVE9YRmpWVVpJV2pCNFVsb3dhREpPUm5BMVVsWndi
  Rk41ZEcxYVYzaElVakJXWVZaVVRYZFVTR2hPWW01c1ExZEhjRlpXTTBKNFMzcGFlVmRFU2xsTlJG
  WnVXa1JXVkZrd1JraE5SVVpMVWtWR1UxWnRkRWxaZW1oUFN6TkNRbVZET1RCVldGSTJUV3BXVkZR
  emF6TmFTSEJZVTBWV2FHSXlOVkpTZWtwaFVUQXhVR042UW1wVE1scFlTekprVW1KdWFFWlVWMUpP
  VTJ4R2EwNHpTa3RMTVUxM1dWWmtTVmxyTlV4ak1XUXhaREpXZUdOSVRtMWphM0JFVld0T2QxSkVi
  RmhpYlhCVFV6Qm9SMDB3T1haTk1FcFVUVEJvZUV3eVJuUlRiSEJXWTBSR2IxRldWak5UYTNOeVpH
  NWtVVXd4VVhwaWJrWnFUbFJPVmxaRk1YSlhSVGxJVjIxR1dHUlZlSFJPVjBwelZqSndURm93YUha
  WFdFMTVZVEpvVm1OWVVrUmFSVlpMV2xaQ1RVMVlaM2hXVmsxM1draHNNRlJ1VGsxUFZrVXdaRWh3
  VDFaSWJIUkxNVXAwVERGV1ZVd3laRXBWTWxKSlRtMUdNVlpxWkZCbGJsWlpaREpKTVZwVlRteE9X
  RkpTV214YVlWTnFiRU5sYWxKWFlURkZNVTFIU2pOa01sWlFWbGQwVTFJelZUTldSV3hUVlRGb2VW
  cElUbEpqYlU1WllqQlNkazVZYkRSVVZXODFUVzFLVDJWc1NsbGFXRTAwWW14Q2NsZFhXa1ZrV0ZK
  WlpGVlNORk42U25aVFJtaDJUbFZqY21GRVNYbFhWRWswVWtoak5WTnVRazFVZWs1WFMzcGFUVk5H
  YUhaYU1WVXdWVEpvV1dGdFpFdFhSMWwzVGtoYU5rc3daR2hqUmxseVdsZGFTRTVyVW5sVFIxbHlU
  VzFrUWs1R2J6RlRSRVpOVjFWV05GWXdOVWhpYkdoRlkwWkNkVmxxV25SWGJWSjJZVzF3VkZveVJt
  aFdhbWhJVFd0a2EyTXlXblJqVkZaTVlrWkthVTVXVGxOaU1sWkNUbTVTTTFORVdYbE5WbFpyVVZk
  S1lWWjZVa1ZTV0dSMFpWVm9jMDFYVGtoVmJXeEpUa1pLVm1KNlNtNVNTRUp5VWxoV2IyRnVUWEpp
  Ym1SVVZFVmFTbUZHU201U01qVk9XVlprY2xkWE1VbFJiVkY2VldwYVYxVlhVbUZVVjJSS1VWZDBX
  VTFHUW5oVU0wcHFWREJXZFZwcldrSlZhWFJ4VVROS01WWXpUazFPUmtZelVsaFNkbUpWVG5CalJW
  SkpVbTVLYUdKWVVuWmhNV1ExVGxkR1FsWXphSHBOYlZJd1pWZHdNMDVIVW5oaVYxcFpWMnhHZVdW
  cVVsbGFlbHBWWWpBME0wNXViM2xaYkU1b1pGTTRNMXB1YkZkVVJtaDJUV3hhU21WR1RuWmtibWh2
  VDFac2VGVnVVazVrTW14aFlUQTBNRXN3YkUxVVJuQk5WRmhTZDFSdE5WbFphelZ1VlRKWmVWZHVi
  RlpVVjJSUVZVVldjbFZzV2xSWFYzaHhWMGhPTUZOWFJUTmxSRWt4VTJwYVYwOVZXalpaTUVwRVZE
  QjRkRmRGT1RaT1ZFSXhUV3RHTTFwNlp6VmthMDB3VG10YU0xcDZWbkpWVkdSTlRUSnNTR1JHUVha
  TE1uUndVa1pDYkdSWFpFbE1NazVVVmpKV1RtRkZXbXBpTUVvMldWVldhRmxyWkhWaVJFcEZZVlZv
  TkZOSFozZGtlVWx6U1cxU2FHUkhSbkphV0d0cFQybEtRbFZWVmtOUlZXaHZaREl3ZDFkWFJrcFZN
  SEJzVlc1U1MySlVWblZOVldNeVpGaEdiRnBYZEZsa1Z6bFpWMFpDYkU1V1ZrZFpNbFUxVlc1Rk5F
  eDZSVEJrTUVaQ1VWVm5NR1F5V2tKWFZYQk1ZakZ3U21GSVdtcFVhMFpTV1RCa2RsSjZhRE5aYkVa
  S1VXdEdSVkZ0T1VOYU1uUjRZVWQwY0ZKNmJETk5SVXBEWkRCV00xTkhaRnBUYkd4S1YydHNRbFl4
  VmtWUmEwWkdaRlV4UTFKVlZrVlZSelZMVWpJeFVWUllaR3BpTWs1dVRrZHNTRTF1WkVwUmExWktV
  VlJqZDFwVmNIQk9SbHBIVmtod00xUkZhRlpSYkZaRldYcEdSVkpWY0d0VFYwNTVWa2hzTkdKV1Ns
  bGlia1l3VWxSc2VHVlZlRkpOYmtFelRURnZNV05JYUhkWlZHeFZXbTEwY0dFd1NUVlhWVmwyWWpC
  U1dGRnFiRUppU0c4eFN6TlJlVkZYZHpWT2VsVjNVRk5KYzBsdVdteGpiazV3WWpJMGFVOXBTWGxK
  YVhkcFpFaHNkMXBUU1RaSmExSkNWa1ZHWmxNd1ZscEphWGRwV2xob2QyRllTbWhrUjJ4MlltbEpO
  azFVWTNwUFJFazBUbnBuTUU0ek1EMD0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8v
  djEvIjogewoJCQkiYXV0aCI6ICJaMkZ5YVd0aGNHRjBhWE5wZG1Gd2NtRnpZV1E2WkdOcmNsOXdZ
  WFJmWkZjMU1qUTRNRmhPZGtObFdVazFUbEZvV1Y5amVWVnNXakZKIgoJCX0sCgkJImh0dHBzOi8v
  aW5kZXguZG9ja2VyLmlvL3YxL2FjY2Vzcy10b2tlbiI6IHsKCQkJImF1dGgiOiAiWjJGeWFXdGhj
  R0YwYVhOcGRtRndjbUZ6WVdRNlpYbEthR0pIWTJsUGFVcFRWWHBKTVU1cFNYTkpibEkxWTBOSk5r
  bHJjRmhXUTBselNXMTBjRnBEU1RaSmJtaFpZVE5DUTJSRVRubFdNMDE1VW5reE1WbHFiSE5qUlhC
  dVkxTktPUzVsZVVwdlpFaFNkMk42YjNaTU1tZ3hXV2sxYTJJeVRuSmFXRWwxV1RJNWRFbHFjRGRK
  YlZaMFdWZHNjMGxxYjJsYU1rWjVZVmQwYUdOSFJqQmhXRTV3WkcxR2QyTnRSbnBaVjFKQllqTldN
  R0pIT1haaGVUVnFZakl3YVV4RFNucGFXRTU2WVZjNWRWZ3liR3RKYW05cFRucENhbHBVVVhwYVYx
  RjBXbTFaZWsxRE1EQlBWRkYzVEZSb2FWcFVhM1JhYlVVeldsUlpNazFFUVRCYWFtdDNTV2wzYVdN
  eU9URmpiVTVzU1dwdmFWbFlWakJoUkVGcFRFTktNV015Vm5saWJVWjBXbE5KTmtsdFpHaGpiV3h5
  V1ZoQ2FHUkhiSHBoV0Zwb1kwaEthR015Um10SmFYZHBaRmhXY0ZwRFNUWkphazEzVGtkSk0xcHFV
  bXBNVjFrd1RsZFpkRTVIVFROTmVURm9UMVJaTlV4VVVYaE9lbFY0V20xR2EwNXRTWGhaYVVvNVRF
  TktjR016VFdsUGFVcHZaRWhTZDJONmIzWk1NbmgyV2pKc2RVeHRVblpaTW5Sc1kyazFhbUl5TUha
  SmFYZHBZek5XYVVscWIybFpXRll3WVVSQ09FMTZRVEJaYW1SdFRrZE5kRnBxVVRGYWFUQXdXWHBq
  ZWt4WFJUVk9hbXQwVGtSRk0wNVVSbTFaVjFFeVdXcEdhVWxwZDJsWldGWnJTV3B3WWtsdGFEQmtT
  RUo2VDJrNGRtRklWbWxNYlZKMldUSjBiR05wTldwaU1qQnBURU5LYjJSSVVuZGplbTkyVERKU2Rs
  a3lkR3hqYVRGM1kyMDVhMHh1Vm5wTWJVWXhaRWRuZDB4dFRuWmlVemt4WXpKV2VXRlhOVzFpZVVw
  a1RFTktjRmxZVVdsUGFrVXpUWHBqTWsxNlNUSk5lbWR6U1cxV05HTkRTVFpOVkdONlRucFplazVx
  U1hwUFEzZHBZekpPZG1OSFZXbFBhVXAyWTBkV2RXRlhVV2RpTWxwdFlrZHNkVnBXT1doWk1rNXNZ
  ek5OYVV4RFNtaGxia0ZwVDJsS1RVNUlXWGRhUnpGelZHdEtkMWRXVm5GU01HUm9XV3BDUkUxcmNE
  QmFNVkp1VjBoSmVGVlliekJhUTBvNUxtaFRVRkozTWprMWNHcGxjbnBMTkRGRE9YRm1WbG90ZFZk
  d2JFZ3pTVzFOU0U4NFRYTjRiVXRETVVONFNubFFRblozWjBGa1FXVmFUVkpZVkhWalV6a3pNM05N
  VkZOQ2NXVXlYMGxSYVV4WU0zTm5hR2sxWWpSNVVUbDJjV1ZOYm1nME1HZEdjakkzTWt0WVUwdE9N
  MnByZW01TWFXUkdWRlZGYmpCRmVXcHJSM2cyVUd4aU4wNU9ZalV3UkdSeFVVWTFhVzV5UzJwa04w
  cDJObTlKUTJaTFVVUklWbUYyVW1zdExUTTJNVXBYUnpGYVZtRmZZVWt4UjI5TWRGaGFTazVKTTNR
  d1dWZEtZMWxtZVhCalEzSjVMV2RuVGt4eGVHZEdiMWxoUWxocExWUnhOMWQzYWxKNU5YRXhZbWx0
  V0RSSmFWOTNNVk51U0VoT00wVXdNR3haY1ZoWFJESk9ibDh3ZDJWRExVTlZTVVJCYlV4QlFUaDRi
  VXhyVUdWalYyVndiVVV5YzFoWFRIbFNXbEZ1UkcxNVZrdHBjVlF4VDJaV1YxcGFRVFZKTkdkM2Iy
  VkpVbGxFWVV4dVdGUnBZVlJmV210MWR3PT0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIu
  aW8vdjEvcmVmcmVzaC10b2tlbiI6IHsKCQkJImF1dGgiOiAiWjJGeWFXdGhjR0YwYVhOcGRtRndj
  bUZ6WVdRNmRqRXVUV05KVUdzNWFrbHZNVE5VYTFScWEweFdNbTk1WVdWMmJrNURUek42YVcxdFVH
  SkJVR2cyU0ZsVVRXeGllRzlKYzNSRFEyazBMVWRUZERGUFNuRnBZMjlGU2tSTFIxVlphVVJ1TjFj
  elVtWlRhWFJEWHpsekxpNU1OSFl3Wkcxc1RrSndXVlZxUjBkaFlqQkRNa3AwWjFSbldISXhVWG8w
  WkE9PSIKCQl9Cgl9LAoJImNyZWRIZWxwZXJzIjogewoJCSJhZnJpY2Etc291dGgxLWRvY2tlci5w
  a2cuZGV2IjogImdjbG91ZCIsCgkJImFzaWEtZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQki
  YXNpYS1lYXN0MS1kb2NrZXIucGtnLmRldiI6ICJnY2xvdWQiLAoJCSJhc2lhLWVhc3QyLWRvY2tl
  ci5wa2cuZGV2IjogImdjbG91ZCIsCgkJImFzaWEtbm9ydGhlYXN0MS1kb2NrZXIucGtnLmRldiI6
  ICJnY2xvdWQiLAoJCSJhc2lhLW5vcnRoZWFzdDItZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwK
  CQkiYXNpYS1ub3J0aGVhc3QzLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJImFzaWEtc291
  dGgxLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJImFzaWEtc291dGgyLWRvY2tlci5wa2cu
  ZGV2IjogImdjbG91ZCIsCgkJImFzaWEtc291dGhlYXN0MS1kb2NrZXIucGtnLmRldiI6ICJnY2xv
  dWQiLAoJCSJhc2lhLXNvdXRoZWFzdDItZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkiYXNp
  YS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkiYXVzdHJhbGlhLXNvdXRoZWFzdDEtZG9ja2VyLnBrZy5k
  ZXYiOiAiZ2Nsb3VkIiwKCQkiYXVzdHJhbGlhLXNvdXRoZWFzdDItZG9ja2VyLnBrZy5kZXYiOiAi
  Z2Nsb3VkIiwKCQkiZG9ja2VyLmV1cm9wZS13ZXN0My5yZXAucGtnLmRldiI6ICJnY2xvdWQiLAoJ
  CSJkb2NrZXIuZXVyb3BlLXdlc3Q4LnJlcC5wa2cuZGV2IjogImdjbG91ZCIsCgkJImRvY2tlci5l
  dXJvcGUtd2VzdDkucmVwLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkiZG9ja2VyLm1lLWNlbnRyYWwy
  LnJlcC5wa2cuZGV2IjogImdjbG91ZCIsCgkJImRvY2tlci51cy1jZW50cmFsMS5yZXAucGtnLmRl
  diI6ICJnY2xvdWQiLAoJCSJkb2NrZXIudXMtY2VudHJhbDIucmVwLnBrZy5kZXYiOiAiZ2Nsb3Vk
  IiwKCQkiZG9ja2VyLnVzLWVhc3QxLnJlcC5wa2cuZGV2IjogImdjbG91ZCIsCgkJImRvY2tlci51
  cy1lYXN0NC5yZXAucGtnLmRldiI6ICJnY2xvdWQiLAoJCSJkb2NrZXIudXMtZWFzdDUucmVwLnBr
  Zy5kZXYiOiAiZ2Nsb3VkIiwKCQkiZG9ja2VyLnVzLWVhc3Q3LnJlcC5wa2cuZGV2IjogImdjbG91
  ZCIsCgkJImRvY2tlci51cy1zb3V0aDEucmVwLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkiZG9ja2Vy
  LnVzLXdlc3QxLnJlcC5wa2cuZGV2IjogImdjbG91ZCIsCgkJImRvY2tlci51cy13ZXN0Mi5yZXAu
  cGtnLmRldiI6ICJnY2xvdWQiLAoJCSJkb2NrZXIudXMtd2VzdDMucmVwLnBrZy5kZXYiOiAiZ2Ns
  b3VkIiwKCQkiZG9ja2VyLnVzLXdlc3Q0LnJlcC5wa2cuZGV2IjogImdjbG91ZCIsCgkJImV1Lmdj
  ci5pbyI6ICJnY2xvdWQiLAoJCSJldXJvcGUtY2VudHJhbDItZG9ja2VyLnBrZy5kZXYiOiAiZ2Ns
  b3VkIiwKCQkiZXVyb3BlLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJImV1cm9wZS1ub3J0
  aDEtZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkiZXVyb3BlLXNvdXRod2VzdDEtZG9ja2Vy
  LnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkiZXVyb3BlLXdlc3QxLWRvY2tlci5wa2cuZGV2IjogImdj
  bG91ZCIsCgkJImV1cm9wZS13ZXN0MTAtZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkiZXVy
  b3BlLXdlc3QxMi1kb2NrZXIucGtnLmRldiI6ICJnY2xvdWQiLAoJCSJldXJvcGUtd2VzdDItZG9j
  a2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkiZXVyb3BlLXdlc3QzLWRvY2tlci5wa2cuZGV2Ijog
  ImdjbG91ZCIsCgkJImV1cm9wZS13ZXN0NC1kb2NrZXIucGtnLmRldiI6ICJnY2xvdWQiLAoJCSJl
  dXJvcGUtd2VzdDYtZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkiZXVyb3BlLXdlc3Q4LWRv
  Y2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJImV1cm9wZS13ZXN0OS1kb2NrZXIucGtnLmRldiI6
  ICJnY2xvdWQiLAoJCSJnY3IuaW8iOiAiZ2Nsb3VkIiwKCQkibWFya2V0cGxhY2UuZ2NyLmlvIjog
  ImdjbG91ZCIsCgkJIm1lLWNlbnRyYWwxLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJIm1l
  LWNlbnRyYWwyLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJIm1lLXdlc3QxLWRvY2tlci5w
  a2cuZGV2IjogImdjbG91ZCIsCgkJIm5vcnRoYW1lcmljYS1ub3J0aGVhc3QxLWRvY2tlci5wa2cu
  ZGV2IjogImdjbG91ZCIsCgkJIm5vcnRoYW1lcmljYS1ub3J0aGVhc3QyLWRvY2tlci5wa2cuZGV2
  IjogImdjbG91ZCIsCgkJIm5vcnRoYW1lcmljYS1zb3V0aDEtZG9ja2VyLnBrZy5kZXYiOiAiZ2Ns
  b3VkIiwKCQkic291dGhhbWVyaWNhLWVhc3QxLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJ
  InNvdXRoYW1lcmljYS13ZXN0MS1kb2NrZXIucGtnLmRldiI6ICJnY2xvdWQiLAoJCSJzdGFnaW5n
  LWs4cy5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkidXMtY2VudHJhbDEtZG9ja2VyLnBrZy5kZXYiOiAi
  Z2Nsb3VkIiwKCQkidXMtY2VudHJhbDItZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkidXMt
  ZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkidXMtZWFzdDEtZG9ja2VyLnBrZy5kZXYiOiAi
  Z2Nsb3VkIiwKCQkidXMtZWFzdDQtZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkidXMtZWFz
  dDUtZG9ja2VyLnBrZy5kZXYiOiAiZ2Nsb3VkIiwKCQkidXMtZWFzdDctZG9ja2VyLnBrZy5kZXYi
  OiAiZ2Nsb3VkIiwKCQkidXMtc291dGgxLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJInVz
  LXdlc3QxLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJInVzLXdlc3QyLWRvY2tlci5wa2cu
  ZGV2IjogImdjbG91ZCIsCgkJInVzLXdlc3QzLWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJ
  InVzLXdlc3Q0LWRvY2tlci5wa2cuZGV2IjogImdjbG91ZCIsCgkJInVzLXdlc3Q4LWRvY2tlci5w
  a2cuZGV2IjogImdjbG91ZCIsCgkJInVzLmdjci5pbyI6ICJnY2xvdWQiCgl9Cn0=
resources: {}
