# Default values for pim-fe application
replicaCount: 1

image:
  repository: 860602188711.dkr.ecr.us-east-1.amazonaws.com/pim-fe
  tag: 28
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

imagePullSecrets:
  - name: my-ecr-secret
imagePullSecretEncoded: |
ewoJImF1dGhzIjogewoJCSI4NjA2MDIxODg3MTEuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdz
LmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsVFZGbzBVekZC
Y2xOcmRISmxSM016VVd0U1VsRXphRlJsYXpWMFRsTjBSV1JHVmpKa1Yyc3dZbTAxTWxwSGVIZGpi
VGcxVjFSQmRsVXlaRE5PTW1SeVpGWkNRbFJwZEc5Wk1qVjJUV3RLYjFSNlNqUlhSRlpFWVVSbk1V
MTZSbGhhVnpoeVdsVm9hV05GWXpKaGFscHJZVlphVDFaR2NEVmpXRVpJV1d4S2VFMVlTa1JSTTFK
RlpGaEpORkpxUW5WbFJWSjNUbTFWZWxOSFNrUlRiVEZvWTFoV2RHTnNUbk5PTWxKUVlrVmFTMXBI
ZUhSWGFsWXpWREF4ZDFWSFNsSlZNbXN5VGxWc1drd3hhRTlWTWxKUVZrWldkazFVWnpKTk1ERk1Z
MnBzZDA1dWNFcE5WM0JzWkVoWk1HTXdaSEZPTWtsNFVsaG9UMk5FUWpWaVdHYzBVMjB3TlV3eFVt
MWlNa1UxVTFjNVNVd3haSHBPYkZKVlkwaGpNR0pYZEdwTmJGRTBUbGQwYVU5VVFUUlZSV2d4VWpB
eFlVMVdRalZXU0ZKS1dtcFNhazFWY0ZsUk1qbHJTekI0UTJGRVZqQlVhazVKVTBSRmNsTnJPSGha
TURsdlpWZGpkMDVXU2s5a1UzUk5WMjFXVVZkSGVFUldSMG96WXpOV1JtVkhaRFZTYTFwRlRrWkpl
bU5xWkhaYVJtaHpWbGRHTVU1cVFUQlhWMGx5VjFWa2MySnRVbmxVUmtwNFlqRmpjbUpGT1hkVWFY
UkxXV3hzY0ZSRk1IWmpNMk42WkZkS2IyVkhUalZOYmxGNFZESkpjbE5YTVRGa01rWk1XVEZvVTAx
V1dtNVNNMnh1VWpCTmVHTjZSblJYUlc5NlRXMVNjRkV6Y0dGVFZrNU1UVzVTY2xVd2JFUk9WVVpK
V1d0U1RsWlZUazlTVm5CNVYwWk5NMlJFU1hKaWVYUnRZMFJDTkZKc1ozZFVia1pQVGxWS2FtRlVW
VEpQUjFZMVdUQTVNMlZWVWxkTlZ6Vm9XbXBHV0ZGck1WTk9lbEYyVTBoTk1HSXpRbk5pYlRGS1N6
QjRObEp1VG5GWmFrWjRWR3BhY0ZaWVFtdFZWR015WlZWb1YxSXdaSFZUYWxKcVZqTldlV0p0ZEhW
aFIzaE5WVzA1Y0dOR2NFbE1NRmt4VDFWS1lXTXhXbWhWVlU1T1lsUkNiMk5XWkZaU2JXeFpTekJL
ZWxwRVNYbFNSbkEwVlROYWRGVnRhSEpOYVhSVFpFZEtWRkpJUW0xVWF6VlJUMFJHY2xSVVl6QmpV
M042WkRCd2ExZEdhSFJXVkdSNlpHeGtVbGxZUlhkVWJYQkpXa1Y0ZG1Sc1pHOVZiR3hDVWpCc2VF
NTZTbGhXV0VZMlpEQldSVlJxYkdoa2EzUk5VbFphUWxkSFduQlNWRUpaVm14c1ZsSjZZM2hYV0Za
eVdUQjBhMDFITlU1a01qVkRWRlJLU2xWRmNGaGxWVVozWW01Q1RVNHhXak5oUkdSWVpVVnJjbEpy
TVVWa01WSnlWVEZTYWxGclRsZGhSMjh6WTBad1ZtUkhXazFoVlZrelkxVndiV0V6WkVkVFYwa3pV
akJKTTFsc1JrNVdNSGQzVW01d1lWWlhSWFpUYlRsWlZtMVNTMU5xUms1WFV6bHRVekpHYmxFeVZU
VmllVGxTVjBob01WTXdlSE5QVlhoVFVtcFNNMlF4UmtsVE1uTjNXVmR3VWxORWFHdFNSMHBUV1dw
S2FHSllRakJpUXpsd1lVUkdSbFpyZEVwT2FUbE9WR3hHVWxOdGFFOVdlazEyV1ZoYWRrdDZRbTFh
VkU1Q1RXMHhTMkZxYkZSaFJWcHJUWHBzWVU5RmVIcE5iRnBxVWxjMU1tUXljM3BYVm5CTVVrVlNR
bVZ1V1RWV1ZrbDZWR3BrUmxNeFZqWldibEoyV25wa2VHSlZNVE5hYmxwTlRrZEdlVXd3WnpCa1ZY
QlZZM3BXYTJGR1pGTlNWM2h4Vm0xd1RtSnJjRmhsYWxwaFdWTTVhMWRITkhsYVV6bHhUakpLYmxG
VVFrdFZSRlV6VlRGc2QyUnRhRVZYUjFaVVlXcHNSR05VUW14U1ZUUjRUMGRLTVUxNlRscFRNbEpW
VVZSc2VGRXdWWHBsUm1zMFZHNWtXVk5GTlVWUFYxcFNWV3hrVlU0d2F6QlVWelZDWW0xNGJFMHlW
bHBUVm1kMlltcFJNMDVxYUdGTU1XczFZbms1ZUU1SVJYZGtNVkY2V210V1dWcEZlR2xUTVhCWFVq
RndkbUpXV1RKa1NFWnhVa1pzUTFkdGVIVmlSbEpJVGtWR1VGUlhaRTlpYTBwSVRXdEtibHA2V2xa
a01rWjZVakpLZDJOV1RqSmtWbkJxVFZWWk1VNVhaRmRTYkVwaFQwWm9SR0ZZVm5ObGFsSllWbGhO
TVZaSFpFSlBSbkJ1V1d4S2VtVkhPVE5PYmxwTVlrZG9kMk14YkhkbFJsRXpWbFZHTldORlpISmpT
RnBXWVVoQk1rMXNaRE5hZWs1TVQxWm9iMUZ1Vm5wT01rWnNaREZhYjJOVlZtbFJVM1F5WWtSak1t
UnRTbmxPU0U0MFZsaFdTMVp0UmtOVFJFMHlVVE5XUTFSdVFsaGhiV3QzWVcwME5GbHVaR0ZYUjJ3
MFYwYzVkVkZVV2xOaFdGWjJXbXhHVUdOWVRUTmtWRUp2VmpBNVdWRlZSbTFVTW1ocFRWY3hUMVl3
V2xOWlZGVjRUWHBzVmxJeWNHOVpiVFZGWVRGYWVGZFlSbnBaTW5kNFZtMUtSR051UmtaT01GcGhV
ak5CZVZOdFpFeFJNRkpPVkVSYWJWVnJSblpQUjJ4aFVsWkNUbUZ1VFhoWmF6RnRZa1JPUlZOV1Fr
bFZiRTVHVFVSS1JtUkhkREJhYkZFMVdtNUNNRlJyVlRCTk1WSnhVVmh3VGxSclVreFZNRkV6VjJ0
c1VsSkRkRk5PZVhSR1dqTldlbUZyTlVoUlZYQjJWbGN3TVVzeVpFeGxhbXhJVmtoV1JWTkdWbTVY
V0ZKQ1RqRnZNR1I1ZERSbFJWb3hWVEp3YVZacE9WZFRhbWhEWlZWc1UySkZSazFqUmxwNVlXcG9i
MVJYVVhKVWJYaDRWVEkxV1ZSSGQzbGlia0pZWVVST1JtSkZUazFXV0dSUFRtNVdSRkpIWkVOVWJX
eEhUV3BrVkU1dGVGTk9iR1J3VFZaQmVGSnJTak5YVkVwVVYxZG9VbFZWWkdGbGJIQnNUMFJGTlZF
eFVsUlViRzk2VWxoR1EySllTa3hVYWs1VFZXdGpOVXd6U205VVJsSTFVVmMxTmxsc1FuWlRWWFJ5
VTBoS2QyUkhjRmxqV0ZJMVdqQldlbFZ1Y0ROWmFYUnpWSGx6ZG1GSFRUSlRiVlowVWpBeE5WWnRX
bkZpYmtKWFYxVnJOVmw2VmxoUmJXeHlXbFpLZWxGck1WUlhWWFEwVWpGR1RHTnRlSFZOVTNSMVpH
eFNkR0l6U21GV1ZFSnBWVE5HU1dGSVZtRlJNRFZoVDFaU1YxcEZNWFZsV0dRelVUSnNiMVZ0Vm5W
WmJrMTVXV3MwZG1GRmVFdFdNRXBJWkRCS2RsbFdVbFZhVjI4MVRrVXhUMk42U2pWUFJuQlpWVmQ0
TlZkRmRHOVpXRTV5V1RKR1RHTldiRWRXYmxwRFZFVnpNazFXVVRKaE0xWm9WMnRzYTAweFRsTmtW
MXBSVGpKNGJGZEZNVVJhVlU1RFpGUk9hMk5ITlhSbFJGRXhXa1pKTTFOVk5VbE5SRlV3VWpCNFZs
ZFZWa3BWTVdoRlYyMXNNRnBHY0hkTlIxVTBUVEZLVGxkV1RteFdWVFZzVGtSQ01GbHNhRWRVVldo
WlRERmtVa2xwZDJsYVIwWXdXVmQwYkdWVFNUWkphMFpTVWxWS1FsTkhhRE5pVkVKYVdWVnNWRk50
VmxOa1JYQjBUbGMwZUZKNldqRmpWMVpzWVRGb01XSXhhRmxWUjFVeFZsVmFhbHBVYkZOalZHZDJU
VlJTTTFGVlJrSlRSRkl6V210R1dsTnJkSFpYYTJ4dlpHMU9UMUZXUm1wU01qbElUMGhrYVZWVmJF
TlJWVkpEWWpCS2JtRXpSbTloTW14SVQxaGpkMUZyU2pOU1dHUkpXakZzUzFkVmJHRlRWVVpZVmxW
U1ExRlZWakZVVlVwR1VsVlNSbFV3TUhaa1ZYaHRXVEJWTWxWWVRuVldNMEpxVlZWc1ExSlZiRUpP
TWtadlpXNUNOazFYYkZoVlZscHNWMWM1UW1Rd09WUldXRXBxVW01Q1VsTkdWbmhhVjFaNlVXeENV
V0p1YTNkVk1rNXhZVlZLZFUxdVpGbExNMHBRV2xaV2JXVlljRXRWVlZwT1ZUQkpkbU5yVms5U1Iz
Y3pVVEk0ZGxKVlVrUmlSbWg2VjJ0a01WRXdhemxKYVhkcFpHMVdlV015YkhaaWFVazJTV3BKYVV4
RFNqQmxXRUpzU1dwdmFWSkZSbFZSVmpsTVVsWnJhVXhEU214bFNFSndZMjFHTUdGWE9YVkphbTk0
VG5wTk0wNTZXWGhQUkZsM1psRTlQUT09IgoJCX0KCX0KfQ==
resources: {}
