apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets[0].name }}
  namespace: pim-fe
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecretEncoded | quote }}
