apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pim-fe
  namespace: pim-fe
  labels:
    app: pim-fe
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pim-fe
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pim-fe
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: pim-fe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}  # Accessing name for each secret in the list
        {{- end }}
