apiVersion: catalog.cattle.io/v1
kind: App
metadata:
  annotations:
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/6RUy27bOhD9lWC2V1Sol2UJuLsARdFFgTbookUWI2pss6ZIgaQcGIb+vSCdJo6dpAGy8oNnhjPnwQMM5LFHj9AeALU2Hr002oWfpvtNwjvyqZUmFei9olSaa9lDCxtSA8NxhORVnLnXZNl6t4UWrndZcvVF6v7/7yQs+X+WaRwIWnCbNNyUWlKEjtJdlrp7uV7v2cMHjiMbUMsVOe/SXfauxm5EEbr3tMJJeZgTEJbi5rdyIOdxGKHVk1IJKOxIvcnHBt0GWuD1oqkWou6X1ORUZ0VV0nJRVF2XYZnV3aLhmchEFW77u93rq8ARdD5pAnGLb7QiS1qQg/bXAXCUP8g6aTS0EDnolBHbrwF6Q4p8PFmhcpSAMNpboxRZaL2dKIGt1EHSR2U+wP0UzbHk5apYNg3jvG5YWWYFa5qeGDZZX3XNsunqCua7OQE3kgjcig1aH7684ceVIvInvOOatH+m5/GMRSBze+dpgOSirpt0r4jFSd9W4LxSmGGQPshRVHUmFjznXVeU1HNe85yTwKKnRbnMi2Uu6rznL/TYEo3MkjOTjfJBlOUFoCO7k4IYCmEmHW4NznkudQ7v9NLuqYanPOX/raVnp1vAPCcx1I/diwSkXpnAfE9OWDkebQSftfOo1JUww6jIx9mldf6GRmX2FGjNeV4xnjFe3/KircqWVz8hZOk9KOfRTy6a/gH6scSckH2eFRxHdx2N+5CB43QDaX/BbH9+dPmKvJTEx3BFNS/1evb/Rcu7E+my+Ymb8BqFUuo/kSaLR2l4Am4aBrR7aA/zPP8JAAD//0lMHdnfBQAA
    objectset.rio.cattle.io/id: helm-app
    objectset.rio.cattle.io/owner-gvk: /v1, Kind=Secret
    objectset.rio.cattle.io/owner-name: sh.helm.release.v1.sample-app.v1
    objectset.rio.cattle.io/owner-namespace: default
  creationTimestamp: '2025-01-07T03:54:06Z'
  generation: 2
  labels:
    objectset.rio.cattle.io/hash: 076956c7d8e92e71354e8635bb1a417b6901c1c5
  managedFields:
    - apiVersion: catalog.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"804f3899-0079-4413-99de-a91d5b989b75"}: {}
        f:spec:
          .: {}
          f:chart:
            .: {}
            f:metadata:
              .: {}
              f:annotations:
                .: {}
                f:fleet.cattle.io/agent-namespace: {}
                f:fleet.cattle.io/bundle-id: {}
                f:fleet.cattle.io/commit: {}
                f:fleet.cattle.io/keep-resources: {}
                f:fleet.cattle.io/service-account: {}
              f:apiVersion: {}
              f:name: {}
              f:version: {}
          f:helmVersion: {}
          f:info:
            .: {}
            f:description: {}
            f:firstDeployed: {}
            f:lastDeployed: {}
            f:status: {}
          f:name: sample-app
          f:namespace: default
          f:resources: {}
          f:version: 1
      manager: agent
      operation: Update
      time: '2025-01-07T03:54:07Z'
    - apiVersion: catalog.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:observedGeneration: {}
          f:summary:
            .: {}
            f:state: {}
      manager: agent
      operation: Update
      subresource: status
      time: '2025-01-07T03:54:07Z'
  name: sample-app
  namespace: default
  ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: false
      controller: true
      kind: Secret
      name: sh.helm.release.v1.sample-app.v1
      uid: 804f3899-0079-4413-99de-a91d5b989b75
  uid: 509d6de4-24e8-4494-8807-3eb07f28e1ea
spec:
  chart:
    metadata:
      annotations:
        fleet.cattle.io/agent-namespace: cattle-fleet-system
        fleet.cattle.io/bundle-id: sample-app
        fleet.cattle.io/commit: d3571c6020bb34ed007020eca3de6482382c72d0
        fleet.cattle.io/keep-resources: 'false'
        fleet.cattle.io/service-account: ''
      apiVersion: v2
      name: sample-app
      version: v0.0.0+git-d3571c6020bb
  helmVersion: 3
  info:
    description: Install complete
    firstDeployed: '2025-01-07T03:54:05Z'
    lastDeployed: '2025-01-07T03:54:05Z'
    status: deployed
  name: sample-app
  namespace: default
  resources:
    - apiVersion: apps/v1
      kind: Deployment
      name: sample-deployment
      namespace: default
    - apiVersion: v1
      kind: Service
      name: sample-service
      namespace: default
  version: 1
status:
  observedGeneration: 2
  summary:
    state: deployed
